### ISSUE TITLE
Step 6 on the 'Run on bluemix'

### ISSUE THREAD

**Issue by vegas3416** [watsonwork/watsonwork-java-starter#4]
It says the run the 'cf push' but doesn't denote that you have to put in a 'app name' for it to actually run the cf push command.

**Comment by ghost** [comment]
So actually when `gradlew build` gets run the name of the app is put into a generated `manifest.yml` file. This file contains the name to use on bluemix, and it defaults to the name of the application according to gradle. This was `java-skeleton-app` and that name was likely taken on bluemix, which would have caused `cf push` to fail. I've cleaned up the docs to recommend that people override the name with `cf push my-app-name` as you suggest, and made it clearer where the default name comes from. Thanks for reporting!

**Comment by vegas3416** [comment]
Is there something else I might be missing here with this 'cf push' command? I'm running through the steps that you have laid out and not quite getting past the cf push part. I do the first 5 steps of the "Run Locally' section and have the app created/registered. I then go to Bluemix do the cmd line for the bluemix login etc..that comes back showing my Org, etc.  I then go into the directory where the starter app is (new name you changed it too) and I run the gradlew clean build. I then am reading below that and it states that if I want to use my own name I need to change the folder name from starter to 'my app name' run the gradlew clean build again and then do the cf push. I do that and run the cf push <my app name> and I see it on BlueMix create the app but on the terminal It gets all the way down to Staging... and then I get an Exit status 222 and eventually a Failed - Error restarting application: NoAppDetectedError   Then it talks about buildpacks and find a list of supported buildpacks. Is there another step that needs to be accounted for so that it works fully or is this project not fully functional and still needs some tweaking to get it to work fully?

**Comment by ghost** [comment]
Ah you're right. The gitignore file meant when I force-updated the repo yesterday that the template to generate the manifest file with didn't also get pushed. I fixed the gitignore just now and went through the steps again with a fresh clone, it works now.

**Comment by vegas3416** [comment]
cool

**Comment by vegas3416** [comment]
I hate to say it but I think there is still something up with the files. I wiped the process out and did everything over again and after I update the config.yml file save it out and try to do a 'gradlew clean build' I get a "Failure: Build failed with an expection" error. Says it failed to capture snapshot of output files for task 'processManifest' property 'destinationDir' during up-to-date check.  And Failed to create MD5 hash for file 'location of where watsonwork file went\.gradle\3.2.1\taskArtifacts\taskArtifacts.lock'

**Comment by ghost** [comment]
Hmm I was hoping the gradle tasks would work on all platforms but this must be an edge case. It sounds like the problem is the gradle copy task is failing because of a file lock, which again may be only affecting windows. 

I can't get a good enough internet connection to download an iso and try this on windows until tomorrow afternoon. I'll write below what I think the problem is and a potential quick workaround, but I'll make sure to test this process on windows tomorrow and let you know about a fix. If you find anything else let me know though, it helps a lot. 

----
From the error message, I believe the problem is that the "destinationDir" for the manifest is the root of the project, and that the copy task is trying to make an md5 hash of that directory. This fails because windows is enforcing that `taskArtifacts.lock` in the `.gradle` folder.

So then the fix will probably be to change where the manifest gets copied to, or how it is generated. 

Assuming the above is correct, a quick workaround would be to go to the build.gradle folder and change the processManifest task to:

```
task processManifest(type: Copy) {
  from 'src/main/resources/manifest.yml'
  into "$rootDir/bluemix"
  filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [APP_NAME: rootProject.name])
}
```

then run `gradlew clean build` and specify where the manifest file is with `cf push -f ./bluemix/manifest.yml`

**Comment by ghost** [comment]
Got the vm and fixed the issue, thanks again for the report :)
