### ISSUE TITLE
Cannot calculate memory: insufficient memory remaining for heap

### ISSUE THREAD

**Issue by gitjps** [watsonwork/watsonwork-java-starter#5]
see [SO](http://stackoverflow.com/questions/42613357/cannot-calculate-memory-insufficient-memory-remaining-for-heap) ; I had to create an availability service in order to continue the installation

**Comment by ghost** [comment]
Hi, thanks for reporting this issue, I was able to reproduce it. I believe the problem was that the java buildpack being used was updated so that it uses more memory by default, meaning the app was trying to use more memory(603532K) than bluemix had allocated(512M). Looking at https://github.com/cloudfoundry/java-buildpack/commits/master there are changes related to memory calculation but I haven't looked into the specifics.

I've added [this change](https://github.com/watsonwork/watsonwork-java-starter/commit/8b6c0abd8e8052f154cc703cdceb77f00d558404) to specify the heap size manually, which fixes this issue. I've also changed it to depend on a buildpack which won't be updating randomly.
